version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql1
    user: root
    networks:
        database:
            aliases:
                - mssql1
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Hm#7K3!yX&1p"
      MSSQL_SA_PASSWORD: "Hm#7K3$yX&1p"
    ports:
      - "1434:1433"

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8080:80"
    networks:
      - database

networks:
    database: